# Generated by Django 3.0.5 on 2023-05-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_number', models.CharField(max_length=64, unique=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('usertype', models.CharField(default='Other', max_length=30)),
                ('usertypesa', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, max_length=64)),
                ('location', models.TextField(blank=True)),
                ('longitude', models.CharField(blank=True, max_length=128)),
                ('latitude', models.CharField(blank=True, max_length=128)),
                ('address', models.TextField(blank=True)),
                ('address_type', models.CharField(default='home', max_length=30)),
                ('language', models.CharField(blank=True, max_length=30)),
                ('admin', models.CharField(blank=True, max_length=30)),
                ('company', models.CharField(blank=True, max_length=60)),
                ('email_verified', models.BooleanField(default=False)),
                ('phone_verified', models.BooleanField(default=False)),
                ('epverifieddate', models.DateTimeField(blank=True)),
                ('epverificationcode', models.CharField(blank=True, max_length=256)),
                ('notes', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(blank=True)),
                ('date_modified', models.DateTimeField(blank=True)),
            ],
        ),
    ]
